export const airlines = {
  "1": "AirOne Polska",
  "666": "Aws express",
  "770": "Samurai Airlines",
  "AAF": "Aigle Azur",
  "AAL": "American Airlines",
  "AAR": "Asiana Airlines",
  "AAW": "Afriqiyah Airways",
  "AAY": "Allegiant Air",
  "ABH": "Aerolineas de Baleares Aebal (Espagne)",
  "ABB": "Air Belgium (Belgique)",
  "ARU": "Aruba airlines (Aruba)",
  "ABQ": "Airblue",
  "ABY": "Air Arabia",
  "ACA": "Air Canada",
  "ACI": "Air Caledonie International",
  "ACK": "Nantucket Airlines (Nouvelle-Angleterre)",
  "ADB": "Antonov Airlines (Ukraine)",
  "ADE": "Ada Air",
  "ADH": "Air One",
  "ADO": "Hokkaido International Airlines",
  "ADR": "Adria Airways",
  "AEA": "Air Europa",
  "AEE": "Aegean Airlines",
  "AEF": "Aero Lloyd (YP)",
  "AEH": "Aviaexpress",
  "AEL": "Air Europe",
  "AEN": "Andorra Airlines",
  "AES": "ACES",
  "AEU": "Astraeus",
  "AEW": "Aerosvit Airlines",
  "AFL": "Aeroflot Russian Airlines",
  "AFR": "Air France",
  "AGN": "Air Gabon",
  "AHK": "Air Hong Kong",
  "AHW": "Aeromist-Kharkiv",
  "AHY": "Azerbaijan Airlines",
  "AIA": "Avies",
  "AIC": "Air India Limited",
  "AIQ": "Thai AirAsia",
  "AIZ": "Arkia Israel Airlines",
  "AJX": "Air Japan",
  "AKL": "Air Kiribati",
  "ALD": "Air Leisure (Égypte)",
  "ALK": "SriLankan Airlines",
  "AMC": "Air Malta",
  "AML": "Air Malawi",
  "AMX": "Aeromexico",
  "ANA": "All Nippon Airways",
  "ANG": "Air Niugini",
  "ANS": "Air Nostrum L.A.M.S.A.",
  "ANZ": "Air New Zealand",
  "APF": "Asia Pacific Airlines (Suède)",
  "APN": "Alpine Airlines (France)",
  "ARG": "Aerolineas Argentinas",
  "ASA": "Alaska Airlines",
  "ASD": "Air Sinai",
  "ASH": "Mesa Airlines",
  "ASL": "Air Serbia",
  "ASZ": "Astrakhan Airlines",
  "AUA": "Austrian Airlines",
  "AUB": "Augsburg Airways",
  "AUH": "Abu Dhabi Amiri Flight",
  "AUI": "Ukraine International Airlines",
  "AUT": "Austral Lineas Aéreas (Argentine)",
  "AUZ": "Australian Airlines",
  "AVA": "Avianca - Aerovias Nacionales de Colombia",
  "AVE": "Avensa",
  "AVI": "L'avion (France)",
  "AVN": "Air Vanuatu",
  "AWI": "Air Wisconsin",
  "AWP": "Air West (France)",
  "AWW": "Air Wales",
  "AXB": "Air India Express",
  "AXM": "AirAsia",
  "AXY": "Axis Airways (France)",
  "AYZ": "Atlant-Soyuz Airlines",
  "AZA": "Alitalia",
  "AZU": "Azul Linhas Aereas (Brésil)",
  "AZW": "Air Zimbabwe",
  "BAG": "dba",
  "BAH": "Thomsonfly (Royaume-Uni)",
  "BAV": "Bamboo Airways (Vietnam)",
  "BAW": "British Airways",
  "BBC": "Biman Bangladesh Airlines",
  "BBG": "Bluebird Airways (Grèce)",
  "BBO": "Flybaboo",
  "BBR": "Santa Barbara Airlines",
  "BCF": "BACH Flugbetriebsges",
  "BCS": "European Air Transport",
  "BCY": "CityJet",
  "BEE": "Flybe",
  "BEL": "Brussels Airlines",
  "BER": "Air Berlin",
  "BHA": "Buddha Air (Népal)",
  "BIE": "Air Mediterranee",
  "BKP": "Bangkok Airways",
  "BLE": "Blue Line",
  "BLV": "Bellview Airlines",
  "BLX": "TUIfly Nordic",
  "BMM": "Atlas Blue",
  "BMR": "BMI Regional (Royaume-Uni)",
  "BOS": "OpenSkies (France)",
  "BOT": "Air Botswana",
  "BOU": "Bouraq Indonesia Airlines",
  "BPA": "Blue Panorama Airlines",
  "BRA": "Braathens (Norvège)",
  "BRU": "Belavia Belarusian Airlines",
  "BRZ": "Samara Airlines (Russie)",
  "BTC": "BAL Bashkirian Airlines",
  "BTI": "Air Baltic",
  "BUB": "Air Bourbon",
  "BWA": "Caribbean Airlines",
  "BYU": "Bayu Indonesia Air (Indonésie)",
  "BZH": "Brit Air",
  "CAI": "Corendon (Turquie)",
  "CAL": "China Airlines",
  "CBJ": "Beijing Capital Airlines",
  "CCA": "Air China",
  "CCM": "Corse-Mediterranee",
  "CDG": "Shandong Airlines",
  "CDO": "Tchadia Airlines (Tchad)",
  "CDN": "Canadian Airlines",
  "CEB": "Cebu Pacific",
  "CES": "China Eastern Airlines",
  "CFG": "Condor Flugdienst",
  "CHF": "Chitaavia",
  "CHP": "Consorcio Aviaxsa",
  "CHQ": "Chautauqua Airlines",
  "CIU": "Cielos del Peru (Pérou)",
  "CLH": "Lufthansa CityLine",
  "CLW": "Centralwings",
  "CMI": "Continental Micronesia",
  "CMP": "Copa Airlines",
  "CND": "Coendon Dutch Airlines (Pays-Bas)",
  "CPA": "Cathay Pacific",
  "CPE": "Cape Air (États-Unis)",
  "CRF": "Air Central",
  "CRK": "Hong Kong Airlines",
  "CRL": "Corsairfly",
  "CSA": "Czech Airlines",
  "CSH": "Shanghai Airlines",
  "CSN": "China Southern Airlines",
  "CST": "Coast Air (Norvège)",
  "CTN": "Croatia Airlines",
  "CUB": "Cubana de Aviacion",
  "CVA": "Air Chathams",
  "CXT": "Coastal Air Transport",
  "CYH": "Yunnan Airlines",
  "DAH": "Air Algerie",
  "DAL": "Delta Air Lines",
  "DAO": "Daallo Airlines",
  "DEX": "Asian Air (Thailand)",
  "DJT": "La Compagnie (France)",
  "DKH": "Juneyao Airlines (Chine)",
  "DKN": "Fly Deccan (Inde)",
  "DLA": "Air Dolomiti",
  "DLH": "Deutsche Lufthansa AG (Allemagne)",
  "DMO": "Domodedovo Airlines",
  "DNV": "Aeroflot-Don",
  "DRK": "Druk Air",
  "DSB": "Air Sénégal",
  "DSL": "Diamond Sakha Airlines",
  "DTA": "TAAG Angola Airlines",
  "DTR": "DAT Danish Air Transport",
  "DUO": "Duo Airways (Royaume-Uni)",
  "EAF": "European AirCharter",
  "EAI": "Emerald Airlines",
  "EDW": "Edelweiss Air",
  "EEZ": "Eurofly (Italie)",
  "EFC": "Air Mana",
  "EIN": "Aer Lingus",
  "ELY": "El Al Israel Airlines",
  "ENK": "Enkor Airlines",
  "ETD": "Etihad Airways",
  "ETH": "Ethiopian Airlines",
  "ETL": "Patterson Aviation Company (États-Unis)",
  "EVA": "EVA Air",
  "EZY": "easyJet",
  "FAB": "First Air",
  "FDB": "Fly Dubai",
  "FDX": "Federal Express",
  "FEY": "FLYeasy (Inde)",
  "FHY": "Free Bird Airlines (Turquie)",
  "FIN": "Finnair",
  "FJI": "Air Pacific Limited t/a Fiji Airways",
  "FLI": "Atlantic Airways",
  "FQA": "Quikjet (Inde)",
  "FRI": "Ibex Airlines (Japon)",
  "FTT": "Frontier Airlines (États-Unis)",
  "FWI": "Air Caraibes",
  "GFA": "Gulf Air",
  "GFL": "Van Air Europe",
  "GGC": "Jetstar Japan",
  "GIC": "Great Lakes Airlines (États-Unis)",
  "GJH": "Jetstar Asia Airways (Singapour)",
  "GLL": "GLL Airlines",
  "GLO": "Gol Linhas Aéreas Inteligentes",
  "GMR": "Air India",
  "GNG": "GoAir (Inde)",
  "GOL": "Gol Linhas Aéreas Inteligentes (Brésil)",
  "GPA": "Guine Bissau Airlines",
  "GPS": "Gippsland Air Services",
  "GWI": "Germanwings",
  "GXL": "Go! (États-Unis - Hawaii)",
  "HAD": "Air D'Ayiti",
  "HAL": "Hawaiian Airlines",
  "HAM": "Haiti Ambassador Airlines",
  "HAT": "Haiti Air",
  "HAV": "Havers Aviation",
  "HBC": "Hebei Airlines",
  "HDA": "Dragonair",
  "HES": "Safi Airways",
  "HFA": "Hahn Air",
  "HIC": "Highland Airways (Royaume-Uni)",
  "HIL": "Hong Kong Airlines",
  "HKA": "HK Express",
  "HLA": "Highland Airways",
  "HNA": "Hainan Airlines",
  "HNB": "Transavia France",
  "HNE": "Horizon Airlines (Australie)",
  "HNK": "Hankyu Airlines",
  "HOG": "Hogestar Airlines",
  "HOP": "HOP! (France)",
  "HPL": "Hewa Bora Airways",
  "HRH": "Royal Tongan Airlines",
  "HRT": "Haiti Air",
  "HSA": "East African Safari Air",
  "HSK": "Hokkaido International Airlines",
  "HSP": "America West Airlines",
  "HTR": "Haiti Air",
  "HTW": "Hatton National Airlines",
  "HUA": "Hainan Airlines",
  "HYE": "Himalaya Airlines",
  "HYV": "Hainan Airlines",
  "IAG": "EPAG - Groupe Air France",
  "IAW": "Iraqi Airways",
  "IBB": "Binter Canarias",
  "IBE": "Iberia Airlines",
  "ICB": "Islandsflug (Islande)",
  "ICE": "Icelandair",
  "IDE": "Independence Air",
  "IGO": "IndiGo Airlines",
  "IRA": "Iran Air",
  "IRC": "Iran Aseman Airlines",
  "IRB": "Iran Air Tours (Iran)",
  "IRM": "Mahan Air",
  "ISR": "Israir",
  "ISS": "Meridiana",
  "ITY": "Italia Trasporto Aereo S.p.A",
  "IWD": "Iberworld (Espagne)",
  "IYE": "Yemenia",
  "JAZ": "JALways",
  "JAW": "Jasmin Airways (Tunisie)",
  "JBA": "Helijet",
  "JBO": "Jambojet (Kenya)",
  "JBU": "JetBlue Airways",
  "JNA": "Jin Air",
  "JON": "Joon (groupe Air France) (France)",
  "JST": "Jetstar Airways",
  "JTA": "Japan Transocean Air",
  "JTG": "Jettime (Danemark)",
  "JXX": "JetX Airlines (Islande/Italie)",
  "JYH": "9 Air (Chine)",
  "KAC": "Kuwait Airways",
  "KAE": "Kartika Airlines (Indonésie)",
  "KAZ": "Tatarstan JSC Aircompany",
  "KFA": "Kelowna Flightcraft",
  "KFB": "Blue1 Oy (précédemment Air Botnia) (Finlande)",
  "KGL": "Kogalymavia Air Company",
  "KHB": "Dalavia",
  "KHO": "Khors Aircompany (Ukraine)",
  "KIL": "Kuban Airlines",
  "KLC": "KLM Cityhopper",
  "KLM": "KLM Royal Dutch Airlines",
  "KMZ": "Comores Aviation",
  "KNE": "Nas Air",
  "KRN": "Karinou Airlines",
  "KQA": "Kenya Airways",
  "KYV": "Cyprus Turkish Airlines (ou Air Kibris) (Chypre, partie occupée par la Turquie)",
  "KZR": "Air Astana",
  "LAA": "Libyan Arab Airlines",
  "LAM": "Linhas A",
  "LAN": "LATAM Airlines Group S.A. dba LATAM Airlines Group",
  "LAP": "TAM Mercosur",
  "LAV": "Aeropostal Alas",
  "LBC": "OpenSkies",
  "LBT": "Nouvel Air Tunisie",
  "LCD": "Líneas Aéreas Azteca (Mexique)",
  "LDA": "Lauda Air",
  "LDI": "Lauda Air S.p.A. (Italie)",
  "LIA": "Leeward Islands Air Transport",
  "LIL": "FlyLal",
  "LIV": "Air Livonia (Estonie)",
  "LLM": "Yamal Airlines",
  "LLR": "Alliance Air",
  "LNI": "Lion Mentari Airlines",
  "LOF": "Trans States Airlines",
  "LOT": "LOT Polish Airlines",
  "LPV": "Air Alps Aviation",
  "LRC": "LACSA",
  "LTE": "Volar Airlines (précédemment LTE International Airways) (Espagne)",
  "LTU": "Air Lituanica",
  "LVG": "Livingston S.p.A. (Italie)",
  "LXR": "Air Luxor",
  "LZB": "Bulgaria Air",
  "MAH": "Malev",
  "MAK": "MAT Macedonian Airlines",
  "MAS": "Malaysia Airlines",
  "MAU": "Air Mauritius",
  "MCK": "Macair Airlines (Australie)",
  "MCM": "Heli Air Monaco",
  "MDA": "Mandarin Airlines",
  "MDG": "Air Madagascar",
  "MEP": "Midwest Connect",
  "MES": "Mesaba Airlines",
  "MGL": "MIAT Mongolian Airlines",
  "MGX": "Montenegro Airlines",
  "MLD": "Air Moldova",
  "MLV": "Magadan Airlines (Russie)",
  "MMA": "Myanmar Airways International (Birmanie)",
  "MMZ": "EuroAtlantic Airways",
  "MNB": "MNG Cargo Airlines",
  "MON": "Monarch Airlines (Royaume-Uni)",
  "MPD": "Air Plus Comet",
  "MPH": "Martinair",
  "MRS": "Marusya Airways",
  "MSI": "Motor Sich",
  "MSR": "Egyptair",
  "MVD": "Kavminvodyavia (Russie)",
  "MVL": "Magadan Airlines",
  "MXA": "Mexicana de Aviaci",
  "MYT": "MyTravel Airways",
  "MYW": "MyAir",
  "NCA": "Nippon Cargo Airlines",
  "NGK": "Oriental Air Bridge (Japon)",
  "NIG": "Aero Contractors",
  "NLY": "Niki",
  "NKS": "Spirit Airlines",
  "NMB": "Air Namibia",
  "NOS": "Neos Airline",
  "NOV": "Alitalia Team (fusionné avec Alitalia en 2002)",
  "NWA": "Northwest Airlines",
  "NWS": "Nordwind (Russie)",
  "OAG": "OAG Worldwide (Royaume-Uni)",
  "OAI": "Olympic Airways (Grèce)",
  "OAS": "Oman Air",
  "OAW": "Helvetic Airways",
  "OCM": "O'Connor Airlines",
  "OGN": "Origin Pacific (Nouvelle-Zélande)",
  "OKS": "Slok Air Gambia",
  "OMS": "Omskavia Airline",
  "ORB": "Orenburg Airlines",
  "PAL": "Philippine Airlines",
  "PAO": "Polynesian Airlines",
  "PDA": "Podillia Avia (Ukraine)",
  "PIA": "Pakistan International Airlines",
  "PIC": "Jetstar Pacific",
  "PLI": "Aeroperu",
  "PLK": "Pulkovo Aviation Entreprise (Russie)",
  "PMN": "UTair (Russie)",
  "PNW": "Palestinian Airlines",
  "PPL": "Air Pegasus",
  "PRI": "Island Air",
  "PUA": "PLUNA",
  "PGT": "Pegasus Airlines (Turquie)",
  "QFA": "Qantas",
  "QXE": "Horizon Air",
  "QTR": "Qatar Airways",
  "RAE": "Régional (compagnie aérienne européenne)",
  "RAM": "Royal Air Maroc",
  "RAR": "Air Rarotonga",
  "RBA": "Royal Brunei Airlines",
  "REA": "Aer Arann",
  "REU": "Air Austral",
  "RIE": "ARIELLA AIRLINES S.A (Burkina Faso)",
  "RIV": "APG Airlines (France)",
  "RJA": "Royal Jordanian",
  "RLA": "Airlinair",
  "RNA": "Nepal Airlines",
  "ROM": "Aeromar",
  "RON": "Nauru Air Corporation",
  "ROT": "Tarom",
  "RPB": "AeroRep",
  "RRE": "Régional Europe (France)",
  "RSO": "Aero Asia International",
  "RSR": "Aero-Service",
  "RTQ": "Air Turquoise (France)",
  "RVL": "Air Vallée (Italie)",
  "RYR": "Ryanair",
  "RZO": "SATA International",
  "SAS": "Scandinavian Airlines System",
  "SAT": "SATA Air Acores",
  "SAY": "Scot Airways (Royaume-Uni)",
  "SBI": "S7 Airlines",
  "SBS": "Seaborne Airlines",
  "SCH": "Schreiner Airways (Pays-Bas)",
  "SCO": "Scoot",
  "SCW": "Braathens Regional Aviation",
  "SCX": "Sun Country Airlines",
  "SDM": "Rossiya-Russian Airlines",
  "SEJ": "SpiceJet (Inde)",
  "SER": "Aero California",
  "SEY": "Air Seychelles",
  "SIA": "Singapore Airlines",
  "SIB": "Sibaviatrans",
  "SIC": "Air Sicilia (Italie)",
  "SHU": "SAT Airlines (Russie)",
  "SJY": "Sriwijaya Air",
  "SKX": "Skyways Express",
  "SKY": "Skymark Airlines",
  "SLK": "SilkAir",
  "SLL": "Slovak Airlines",
  "SLM": "Surinam Airways",
  "SOV": "Saratov Aviation Division",
  "SPM": "Air Saint Pierre",
  "SRQ": "South East Asian Airlines",
  "SSV": "Skyservice Airlines",
  "SUD": "Sudan Airways",
  "SVA": "Saudi Arabian Airlines",
  "SVK": "Air Slovakia",
  "SVR": "Ural Airlines",
  "SWA": "Southwest Airlines",
  "SWD": "Southern Winds Airlines",
  "SWG": "Sunwing Airlines",
  "SWR": "Swiss International Air Lines",
  "SWU": "Swiss Global Air Lines",
  "SYR": "Syrianair",
  "TAI": "Avianca El Salvador",
  "TAM": "TAM Brazilian Airlines",
  "TAO": "Aeromar (Mexique)",
  "TAP": "TAP Portugal",
  "TAR": "Tunisair",
  "TAX": "Thai AirAsia X",
  "TCV": "TACV",
  "TCW": "Thomas Cook Airlines",
  "TCX": "Thomas Cook Airlines UK",
  "TDM": "Tandem Aero",
  "TGA": "Air Togo",
  "TGW": "Tiger Airways",
  "TGZ": "Georgian Airways",
  "THA": "Thai Airways International",
  "THT": "Air Tahiti Nui",
  "THY": "Turkish Airlines",
  "TJT": "Twin Jet",
  "TLB": "Atlantique Air Assistance (France)",
  "TMA": "Trans Mediterranean Airways (TMA)",
  "TMN": "Tasman Cargo Airlines (Australie/Nouvelle-Zélande)",
  "TPC": "Air Cal",
  "TRA": "Transavia Holland",
  "TRJ": "Trujet (Inde)",
  "TRZ": "Prime Air Inc.",
  "TSC": "Air Transat",
  "TUA": "Turkmenistan Airlines",
  "SEN": "Tunisair Express (ex Sevenair)",
  "TUQ": "Air Turquoise",
  "TVF": "Transavia France (France)",
  "TVR": "Tavrey Airlines",
  "TVS": "Travel Service Airlines",
  "TYR": "Tyrolean Airways",
  "UAE": "Emirates",
  "UAL": "United Airlines",
  "UBA": "Myanma Airways",
  "UCR": "Aero-Charter Ukraine",
  "UDC": "Donbassaero (Ukraine)",
  "UDN": "Dniproavia (Ukraine)",
  "UIA": "Uni Air",
  "UKM": "UM Airlines",
  "UKR": "Air Ukraine",
  "UKS": "Ukrainian Cargo Airways",
  "UKW": "Lviv Airlines",
  "URG": "Air Urga",
  "URP": "?? ARP 410 Airlines (Ukraine)",
  "UYC": "Cameroon Airlines",
  "UTA": "UTair Aviation",
  "UZB": "Uzbekistan Airways",
  "VAP": "Phuket Air",
  "VDA": "Volga-Dnepr Airlines",
  "VIR": "Virgin Atlantic Airways",
  "VLE": "Volare Web Volare Airlines SpA (Italie)",
  "VLG": "Vueling Airlines (Espagne)",
  "VLK": "Vladivostok Air",
  "VLU": "Valuair",
  "VOE": "Volotea (Espagne)",
  "VOZ": "Virgin Australia",
  "VRD": "Virgin America",
  "VRE": "Volare Airlines (Ukraine)",
  "VSP": "VASP",
  "VTA": "Air Tahiti",
  "VTI": "Air Vistara",
  "VUN": "Air Ivoire",
  "WAK": "Wings of Alaska",
  "WBA": "Finncomm Airlines",
  "WCP": "Primaris Airlines",
  "WIA": "Winair",
  "WIF": "Wideroe's Flyveselskap",
  "WJA": "WestJet",
  "WOA": "World Airways",
  "WZZ": "Wizz Air",
  "XAR": "Xpress Air",
  "XAX": "AirAsia X",
  "XJC": "Xclusive Jet Charter",
  "XLF": "XL Airways France (ex Star Airlines)",
  "XRC": "Express Air Cargo (Tunisie)",
  "YZR": "Yangtze River Express Airlines",
  "ZAL": "Zoom Air (Inde)",
  "ZBA": "Air",
  "ZWA": "flymojo (Malaisie)",
  "FBU": "French Bee",
  "BMA": "Bermudair",
  "SIL": "Silver Airways LLC",
  "ART": "SmartLynx Airlines",
  "DWI": "Arajet Airlines",
  "FPY": "Play Airlines",
  "ZZZ": "Ryola Airline",
  "CBF": "Cascadia Air",
  "FRS": "Ryola Airlines International",
  "WEW": "West Wind",
  "NAL": "Northway Aviation",
  "NTA": "NT Air",
  "MAL": "Morningstar Air Express",
  "KDC": "KD Air",
  "IAX": "IAXpress",
  "IRO": "CSA Air Express Air Cargo",
  "LBR": "Air Borealis",
  "ENJ": "Enerjet",
  "PSC": "Pascan",
  "EVS": "EVAS Air Charters",
  "CRQ": "AirCreebec",
  "WSG": "Wasaya Airways",
  "LCO": "LATAM Cargo",
  "PVL": "PAL Airlines",
  "FLE": "Flair Airlines",
  "GLR": "Central Mountain Air",
  "AIJ": "Interjet",
  "AIE": "Air Inuit",
  "3AB": "Ryola Air",
  "OOM": "Zoom Airlines",
  "WZP": "Zip",
  "ZNA": "Zenith International Airline",
  "ZTT": "ZABAIKAL AIRLINES",
  "YEL": "Yellowtail",
  "SEU": "XL Airways France",
  "CXA": "Xiamen Airlines",
  "XAU": "XAIR USA",
  "WE1": "World Experience Airline",
  "WAU": "Wizz Air Ukraine",
  "JET": "Wind Jet",
  "CHB": "West Air China",
  "WLC": "Welcome Air",
  "WEB": "WebJet Linhas A",
  "6CC": "Vuela Cuba",
  "VRN": "VRG Linhas Aereas",
  "VC9": "Volotea Costa Rica",
  "VOI": "Volaris",
  "K88": "Voestar",
  "VLM": "VLM Airlines",
  "TZP": "Zipair Tokyo",
  "VWA": "Virginwings",
  "VNP": "Virgin Pacific",
  "VGN": "Virgin Nigeria Airways",
  "VEX": "Virgin Express",
  "MOV": "VIM Airlines",
  "VKH": "Viking Hellas",
  "HVN": "Vietnam Airlines",
  "VOA": "Viaggio Air",
  "VLO": "Varig Log",
  "GWY": "USA3000 Airlines",
  "ES2": "Usa Sky Cargo",
  "JUS": "USA Jet Airlines",
  "USA": "US Airways",
  "UPS": "United Parcel Service",
  "UBD": "United Airways",
  "URN": "Turan Air",
  "TUI": "Tuninter",
  "HLX": "TUIfly",
  "TP3": "TROPICAL LINHAS AEREAS",
  "TOS": "Tropic Air",
  "TIB": "TRIP Linhas A",
  "TBZ": "TrasBrasil",
  "RGG": "TransRussiaAirlines",
  "TYS": "TransHolding System",
  "THS": "TransBrasil Airlines",
  "TNA": "TransAsia Airways",
  "TSO": "Transaero Airlines",
  "TWA": "Trans World Airlines",
  "TMW": "Trans Maldivian Airways",
  "TLM": "Tramm Airlines",
  "TOL": "Tol-Air Services",
  "AWC": "Titan Airways",
  "TNM": "Tiara Air",
  "T33": "THREE",
  "TOM": "Thomsonfly",
  "TSX": "Thai Star Airlines",
  "TCG": "Thai Air Cargo",
  "TAK": "Tatarstan Airlines",
  "DTH": "Tassili Airlines",
  "TPA": "TAMPA",
  "TAE": "TAME",
  "TJA": "T.J. Air",
  "SWV": "Swe Fly",
  "SXS": "SunExpress",
  "ERO": "Sun D'Or",
  "SNB": "Sterling Airlines",
  "SFJ": "Star Flyer",
  "CQH": "Spring Airlines",
  "MNP": "Spirit of Manila Airlines",
  "JKK": "Spanair",
  "ZCS": "Southjet connect",
  "XAN": "Southjet cargo",
  "SJS": "Southjet",
  "SAA": "South African Airways",
  "SOL": "Solomon Airlines",
  "TLK": "Starlink Aviation",
  "QER": "SOCHI AIR CHATER",
  "KOL": "SOCHI AIR",
  "SKW": "SkyWest",
  "SYX": "Skywalk Airlines",
  "SNJ": "Skynet Asia Airways",
  "SIH": "Skynet Airlines",
  "ESK": "SkyEurope",
  "SRK": "Sky Work Airlines",
  "SXR": "Sky Express",
  "SKU": "Sky Airline",
  "SIT": "SITA",
  "AZQ": "Silk Way Airlines",
  "SRH": "Siem Reap Airways",
  "CSC": "Sichuan Airlines",
  "TCF": "Shuttle America",
  "CSZ": "Shenzhen Airlines",
  "SAI": "Shaheen Air International",
  "STU": "Servicios de Transportes A",
  "SA1": "Serbian Airlines",
  "SGG": "Senegal Airlines",
  "SOZ": "Sat Airlines",
  "SMY": "Sama Airlines",
  "SLC": "Salsa d\\\\'Haiti",
  "RYN": "Ryan International Airlines",
  "RWD": "Rwandair Express",
  "RS1": "Royal Southern Airlines.",
  "RFJ": "Royal Falcon",
  "ROB": "ROYAL BRITAIN",
  "RPK": "Royal Airlines",
  "RSL": "Rio Sul Servi",
  "RLE": "Rico Linhas A",
  "RXR": "REXAIR VIRTUEL",
  "RPH": "Republic Express Airlines",
  "CEA": "RegionsAir",
  "2K2": "Regionalia Uruguay",
  "CR1": "Regionalia Chile",
  "REP": "Regional Paraguaya",
  "RXA": "Regional Express",
  "N78": "Regional Air Iceland",
  "REK": "Reem Air",
  "RWZ": "Red Wings",
  "RNY": "Rainbow Air US",
  "RAY": "Rainbow Air Canada",
  "RAB": "Rainbow Air (RAI)",
  "PWF": "Private Wings Flugcharter",
  "PSD": "President Airlines",
  "PRF": "Precision Air",
  "PDC": "Potomac Air",
  "PGA": "Portugalia",
  "POE": "Porter Airlines",
  "PMT": "PMTair",
  "FLG": "Pinnacle Airlines",
  "PDT": "Piedmont Airlines (1948-1989)",
  "PGP": "Perm Airlines",
  "PEN": "Peninsula Airways",
  "PBA": "PB Air",
  "PMW": "Paramount Airways",
  "PQW": "PanAm World Airways",
  "PNR": "PAN Air",
  "PMK": "Palair Macedonia",
  "NMI": "Pacific Wings",
  "PEC": "Pacific East Asia Cargo Airlines",
  "PCO": "Pacific Coastal Airline",
  "PBN": "Pacific Blue",
  "OZJ": "Ozjet Airlines",
  "FJM": "Fly Jumaica Airways",
  "OLT": "Ostfriesische Lufttransport",
  "OEA": "Orient Thai Airlines",
  "ORC": "Orchid Airlines",
  "OAB": "Orbit Airlines Azerbaijan",
  "OSY": "Open Skies Consultative Commission",
  "1CH": "OneChina",
  "OAE": "Omni Air International",
  "OMA": "Oman Air",
  "OAL": "Olympic Airlines",
  "ONE": "Oceanair",
  "VCX": "Ocean Airlines",
  "OHK": "Oasis Hong Kong Airlines",
  "NAX": "Norwegian Air Shuttle",
  "PLR": "Northwestern Air",
  "NRD": "Nordic Regional",
  "NGB": "Nordic Global Airlines",
  "NES": "Nordeste Linhas Aereas Regionais",
  "NOK": "Nok Air",
  "NIA": "Nile Air",
  "NTJ": "NextJet",
  "NXB": "NEXT Brasil",
  "NEA": "New England Airlines",
  "NTW": "Nationwide Airlines",
  "NJS": "National Jet Systems",
  "NAS": "Nasair",
  "MTC": "Mountain Air Company",
  "GAI": "Moskovia Airlines",
  "ZTF": "Mongolian International Air Lines ",
  "MDV": "Moldavian Airlines",
  "RPA": "Republic Airways",
  "MDW": "Midway Airlines",
  "MEA": "Middle East Airlines",
  "MJG": "Michael Airlines",
  "MXI": "MexicanaLink",
  "BTV": "Metro Batavia",
  "MNA": "Merpati Nusantara Airlines",
  "MNJ": "Menajet",
  "MYD": "Maya Island Air",
  "MXJ": "Maxjet Airways",
  "MXL": "Maxair",
  "MAI": "Mauritania Airlines International",
  "MKD": "MAT Airways",
  "1QA": "Marysya Airlines",
  "M1F": "Maryland Air",
  "MSL": "Marsland Aviation",
  "MNO": "Mango",
  "MDL": "Mandala Airlines",
  "MXD": "Malindo Air",
  "MAV": "Maldivo Airlines",
  "MZS": "Mahfooz Aviation",
  "LYC": "Lynden Air Cargo",
  "LGL": "Luxair",
  "LTR": "Lufttransport",
  "LTF": "Lufttaxi Fluggesellschaft",
  "GEC": "Lufthansa",
  "LGW": "Luftfahrtgesellschaft Walter",
  "LJJ": "Luchsh Airlines ",
  "LOO": "LSM Airlines",
  "LOC": "Locair",
  "LLB": "Lloyd Aereo Boliviano",
  ":::": "Llloyd Helicopters",
  "LIX": "LionXpress",
  "LER": "Linea Aerea de Servicio Ejecutivo Regional",
  "LTY": "Liberty Airways",
  "LMM": "LCM AIRLINES",
  "LPN": "Laoag International Airlines",
  "LAO": "Lao Airlines",
  "LPE": "LATAM Airlines Peru",
  "LXP": "LAN Express",
  "DSM": "LAN Argentina",
  "BNX": "LAI - Linea Aerea IAACA",
  "JEV": "Lagun Air",
  "LPR": "L",
  "NRL": "Nolinor Aviation",
  "KZU": "Kuzu Airlines Cargo",
  "KPA": "Kunpeng Airlines",
  "KRI": "Krylo Airlines",
  "KJC": "Krasnojarsky Airlines",
  "KOQ": "Kostromskie avialinii",
  "KGO": "Korongo Airlines",
  "KAL": "Korean Air",
  "KBR": "KoralBlue Airlines",
  "DAT": "Lynx Air",
  "KFR": "Kingfisher Airlines",
  "KHK": "Kharkiv Airlines",
  "KEN": "Kenmore Air",
  "KNI": "KD Avia",
  "SKV": "SkyRegional",
  "AKT": "Karat",
  "KMP": "Kampuchea Airlines",
  "KMF": "Kam Air",
  "CKS": "Kalitta Air",
  "JAV": "Jordan Aviation",
  "JTO": "Jettor Airlines",
  "JEC": "Jett8 Airlines Cargo",
  "JSA": "Jetstar Asia Airways",
  "JGO": "JetsGo",
  "JCS": "Jetclub",
  "JAF": "Jetairfly",
  "JFU": "Jet4You",
  "EXS": "Jet2.com",
  "JAI": "Jet Airways",
  "JJA": "Jeju Air",
  "JTY": "Jatayu Airlines",
  "JAA": "Japan Asia Airways",
  "JAL": "Japan Airlines",
  "JEX": "JAL Express",
  "ACL": "Itali Airlines",
  "ISV": "Islena De Inversiones",
  "ISW": "Islas Airways",
  "SDY": "Island Express",
  "MKU": "Island Air (WP)",
  "FWA": "Interstate Airline",
  "ISK": "Intersky",
  "INE": "International Europe",
  "IBZ": "International Business Air",
  "ITK": "Interlink Airlines",
  "ICT": "Intercontinental de Aviaci",
  "ILN": "Interair South Africa",
  "IIN": "Inter Islands Airlines",
  "IAA": "Indonesian Airlines",
  "IDS": "Indonesia Sky",
  "AWQ": "Indonesia AirAsia",
  "IAC": "Indian Airlines",
  "IIR": "INAVIA Internacional",
  "ITX": "Imair Airlines",
  "IBX": "Ibex Airlines",
  "IBS": "Iberia Express",
  "CSQ": "IBC Airways",
  "HKE": "Hong Kong Express Airways",
  "HOA": "Hola Airlines",
  "HFY": "Hi Fly",
  "HER": "Hex'Air",
  "LSJ": "Air Liaison",
  "NWL": "North-Wright Airways",
  "HEY": "Hellenic Airways",
  "HEJ": "Hellas Jet",
  "HCY": "Helios Airways",
  "HFR": "Heli France",
  "HMY": "Harmony Airways",
  "HAR": "Harbor Airlines",
  "HLF": "Hapagfly",
  "HNX": "Hankook Airline",
  "HA1": "Hankook Air US",
  "HHI": "Hamburg International",
  "CHH": "Hainan Airlines",
  "HAG": "Hageland Aviation Services",
  "GU1": "Gulisano airways",
  "GIF": "Guinee Airlines",
  "BSR": "Guine Bissaur Airlines",
  "GFY": "Greenfly",
  "GWL": "Great Wall Airlines",
  "GLA": "Great Lakes Airlines",
  "IKA": "Gorkha Airlines",
  "GAO": "Golden Air",
  "GLP": "Globus",
  "GA0": "Global Airlines",
  "GHB": "Ghana International Airlines",
  "GXG": "GermanXL",
  "GMI": "Germania",
  "GFG": "Georgian National Airlines",
  "GBL": "GB Airways",
  "GZP": "Gazpromavia",
  "GIA": "Garuda Indonesia",
  "GNF": "Gandalf Airlines",
  "GNR": "Gambia International Airlines",
  "GDR": "Gadair European Airlines",
  "GBK": "Gabon Airlines",
  "FTA": "Frontier Flying Service",
  "FFT": "Frontier Airlines",
  "FRE": "Freedom Air",
  "X9F": "FRA Air",
  "FSC": "Four Star Aviation / Four Star Cargo",
  "FOS": "Formosa Airlines",
  "FPT": "FlyPortugal",
  "NDC": "FlyNordic",
  "FHI": "FlyHigh Airlines Ireland (FH)",
  "FFV": "Fly540",
  "OTJ": "Fly Romania",
  "FLY": "Fly Me Sweden",
  "ILY": "Fly Illi",
  "FRF": "Fly France",
  "3FF": "Fly Colombia ( Interliging Flights )",
  "FBL": "Fly Brasil",
  "FLM": "Fly Air",
  "FWL": "Florida West International Airways",
  "FCL": "Florida Coastal Airlines",
  "FLT": "Flightline",
  "FFR": "Fischer Air",
  "FCA": "First Choice Airways",
  "FFM": "Firefly",
  "FNC": "Finalair Congo",
  "NCR": "National Airlines",
  "FXX": "Felix Airways",
  "FSW": "Faso Airways",
  "RCK": "Faroejet",
  "EFA": "Far Eastern Air Transport",
  "BTA": "ExpressJet",
  "LHN": "Express One International",
  "EXV": "Expo Aviation",
  "EXK": "Executive Airlines",
  "EXA": "Execair Aviation",
  "XLA": "Excel Airways",
  "EIA": "Evergreen International Airlines",
  "EWG": "Eurowings",
  "EAL": "European Air Express",
  "EMX": "Euromanx Airways",
  "ELO": "Eurolot",
  "MJX": "Euroline",
  "ECA": "Eurocypria Airlines",
  "ELL": "Estonian Air",
  "ESF": "Estafeta Carga Aerea",
  "ERT": "Eritrean Airlines",
  "RVF": "Ravn Alaska",
  "4AA": "Epic Holiday",
  "ESS": "Eos Airlines",
  "EEA": "Empresa Ecuatoriana De Aviacion",
  "BRQ": "El-Buraq Air Transport",
  "ELA": "Eastland Air",
  "EAV": "Eastern Atlantic Virtual Airlines",
  "EZE": "Eastern Airways",
  "UGX": "East African",
  "DOA": "Dominicana de Aviaci",
  "MDO": "Domenican Airlines",
  "IBK": "Norweigan Air International",
  "DHX": "DHL International",
  "JOS": "DHL de Guatemala",
  "AMB": "Deutsche Rettungsflugwacht",
  "DC2": "Dense Connection",
  "DWA": "Dense Airways",
  "DSY": "Dennis Sky",
  "DAU": "Dauair",
  "DWT": "Darwin Airline",
  "DAG": "Dagestan Airlines",
  "CYP": "Cyprus Airways",
  "ECC": "Crossair Europe",
  "COZ": "Cosmic Air",
  "CX0": "Copenhagen Express",
  "VCV": "Conviasa",
  "COA": "Continental Airlines",
  "KIS": "Contact Air",
  "MXC": "Compania Mexicargo",
  "CWK": "Comores Airlines",
  "UCA": "CommutAir",
  "COM": "Comair",
  "CJC": "Colgan Air",
  "ISG": "Club Air",
  "CAT": "Civil Air Transport",
  "SDR": "City Airline",
  "RUS": "Cirrus Airlines",
  "CIM": "Cimber Air",
  "YCC": "Ciel Canadien",
  "CQN": "Chongqing Airlines",
  "CXH": "China Xinhua Airlines",
  "CUA": "China United Airlines",
  "CNW": "China Northwest Airlines",
  "CKK": "China Cargo Airlines",
  "WDY": "Chicago Express",
  "FQR": "CheapFlyingInternational",
  "CSU": "Chari Aviation Services",
  "CGN": "Changan Airlines",
  "CCP": "Champion Air",
  "CWC": "Centurion Air Cargo",
  "CVC": "Centre-Avia",
  "CNA": "Centavia",
  "CCC": "CCML Airlines",
  "CIF": "CB Airways UK ( Interliging Flights )",
  "CAY": "Cayman Airways",
  "KRP": "Carpatair",
  "ZYZ": "Caribbean Wings",
  "CJT": "Cargojet Airways",
  "CRG": "Cargoitalia",
  "CGP": "Cargo Plus Aviation",
  "CCI": "Capital Cargo International Airlines",
  "KAP": "Cape Air",
  "CA1": "CanXpress",
  "CAP": "CanXplorer",
  "CJA": "CanJet",
  "CNN": "Canadian World",
  "CWA": "Canadian Western Airlines",
  "MPE": "Canadian North",
  "YCP": "Canadian National Airways",
  "CAM": "Camai Air",
  "CLI": "Calima Aviacion",
  "CWS": "California Western",
  "ICL": "CAL Cargo Air Lines",
  "BCC": "BusinessAir",
  "BFL": "Buffalo Airways",
  "BG1": "BudgetAir",
  "LAJ": "British Mediterranean Airways",
  "BIH": "British International Helicopters",
  "BRV": "Bravo Air Congo",
  "BRB": "BRA-Transportes Aereos",
  "BNF": "Braniff International Airways",
  "BTQ": "Boutique Air (Priv)",
  "CXS": "Boston-Maine Airways",
  "WOW": "Wow Air",
  "BLF": "Blue1",
  "BWG": "Blue Wings",
  "JOR": "Blue Air",
  "BML": "Bismillah Airlines",
  "BSY": "Big Sky Airlines",
  "BVT": "Berjaya Air",
  "BRG": "Bering Air",
  "BGL": "Benin Golf Air",
  "BMJ": "Bemidji Airlines",
  "ABS": "Transwest Air",
  "PAG": "Perimeter Aviation LP dba Bearskin Airlines",
  "BYE": "Bayu Indonesia Air",
  "BSX": "Bassaka airlines",
  "NKF": "Barents AirLink",
  "BA1": "Baltic Air lines",
  "BAJ": "Baker Aviation",
  "BUU": "Baikotovitchestrian Airlines ",
  "BHS": "Bahamasair",
  "CFE": "BA CityFlyer",
  "VLI": "Avolar Aerolineas",
  "VXG": "Avirex",
  "SMJ": "Avient Aviation",
  "TWN": "Avialeasing Aviation Company",
  "AOC": "AVCOM",
  "CJL": "Canada Jetlines",
  "AUR": "Aurigny Air Services",
  "JOL": "Atyrau Air Ways",
  "VAS": "ATRAN Cargo Airlines",
  "KKK": "Atlasjet",
  "GTI": "Atlas Air",
  "LUR": "Atlantis European Airways",
  "ASQ": "Atlantic Southeast Airlines",
  "A1F": "Atifly",
  "ACP": "Astral Aviation",
  "DHL": "Astar Air Cargo",
  "AAS": "Askari Aviation",
  "AWM": "Asian Wings Airways",
  "RIT": "Asian Spirit",
  "AXF": "Asian Express Airlines",
  "AWA": "Asia Wings",
  "AOT": "Asia Overnight Express",
  "OCA": "Aserca Airlines",
  "APW": "Arrow Air",
  "RML": "Armenian International Airways",
  "RNV": "Armavia",
  "TFL": "Arkefly",
  "ARA": "Arik Air",
  "AFG": "Ariana Afghan Airlines",
  "AZE": "Arcus-Air Logistic",
  "CIR": "Arctic Circle Air Service",
  "IWA": "Apache Air",
  "AOM": "AOM French Airlines",
  "ABV": "Antrak Air",
  "DJA": "Antinea Airlines",
  "AAA": "Ansett Australia",
  "AAN": "Amsterdam Airlines",
  "AJT": "Amerijet International",
  "EGF": "American Eagle Airlines",
  "AWE": "America West Airlines",
  "GNT": "Amber Air",
  "AZN": "Amaszonas",
  "AGT": "Amadeus Global Travel Distribution",
  "DRU": "Alrosa Mirny Air Enterprise",
  "AIP": "Alpine Air Express",
  "ELG": "Alpi Eagles",
  "AAH": "Aloha Airlines",
  "LMU": "AlMasria Universal Airlines",
  "UTY": "Alliance Airlines",
  "GRO": "Allegro",
  "N77": "All Spain",
  "N99": "All Europe",
  "8K8": "All Australia",
  "AL3": "All Asia",
  "Z9H": "All Argentina Express",
  "0MM": "All America MX",
  "7ZC": "All America CO",
  "R1R": "All America CL",
  "A9B": "All America BR",
  "PYB": "All America BOPY",
  "M7A": "All America AR",
  "AL2": "All America",
  "99F": "All Africa",
  "SMX": "Alitalia Express",
  "LID": "Alidaunia",
  "NBK": "Albarka Air",
  "AER": "Alaska Central Express",
  "TRS": "AirTran Airways",
  "RRJ": "AirRussia",
  "ANO": "Airnorth",
  "ZAK": "Airlink Zambia",
  "TOK": "Airlines PNG",
  "ATM": "Airlines Of Tasmania",
  "ARE": "Aires",
  "SYL": "Aircompany Yakutia",
  "OCN": "Discover Airlines",
  "ABW": "AirBridge Cargo",
  "VIM": "Air VIA",
  "VGA": "Air Vegas",
  "ATC": "Air Tanzania",
  "SBK": "Air Srpska",
  "AGB": "Air Service Gabon",
  "SNG": "Air Senegal International",
  "SDO": "Air Santo Domingo",
  "RNE": "Air Salone",
  "RSH": "Air Sahara",
  "EQL": "Air S",
  "GAP": "Air Philippines",
  "PRZ": "Air Paradise International",
  "ANE": "Air Nostrum",
  "ANT": "Air North Charter - Canada",
  "AKX": "Air Nippon Network Co. Ltd.",
  "ANK": "Air Nippon",
  "RCH": "Air Mobility Command",
  "AMW": "Air Midwest",
  "MKG": "Air Mekong",
  "MRT": "Air Mauritanie",
  "CWM": "Air Marshall Islands",
  "DRD": "Air Madrid",
  "AMU": "Air Macau",
  "LXG": "Air Luxor GB",
  "KLA": "Air Lithuania",
  "KOR": "Air Koryo",
  "KZK": "Air Kazakhstan",
  "AJM": "Air Jamaica",
  "AEY": "Air Italy",
  "AI0": "Air Indus",
  "FXI": "Air Iceland",
  "HZT": "Air Horizon",
  "AHO": "Air Hamburg (AHO)",
  "GRL": "Air Greenland",
  "AGV": "Air Glaciers",
  "GGN": "Air Georgian",
  "GRG": "Air Georgia",
  "UPA": "Air Foyle",
  "FLZ": "Air Florida",
  "FIF": "Air Finland",
  "FAJ": "Air Fiji",
  "AXL": "Air Exel",
  "CRD": "Air Corridor",
  "ABR": "Air Contractors",
  "HAH": "Air Comores International",
  "QCL": "Air Class Lineas Aereas",
  "ECE": "Air City",
  "SNC": "Air Cargo Carriers",
  "JZA": "Air Canada Jazz",
  "ABL": "Air Busan",
  "PBU": "Air Burundi",
  "VBW": "Air Burkina",
  "BON": "Air Bosna",
  "BGD": "Air Bangladesh",
  "ABD": "Air Atlanta Icelandic",
  "ARR": "Air Armenia",
  "RBG": "Air Arabia Egypt",
  "AOW": "Air Andaman (2Y)",
  "AHA": "Air Alpha Greenland",
  "RKA": "Air Afrique",
  "GUI": "Aguilar Connect",
  "AFU": "Afrinat International Airlines",
  "QSC": "African Safari Airways",
  "WTA": "Africa West",
  "ATI": "Aero-Tropics Air Services",
  "RSU": "Aerosur",
  "PEL": "Aeropelican Air Services",
  "MPX": "Aeromexpress",
  "SLI": "Aerolitoral",
  "GLG": "Aerolineas Galapagos (Aerogal)",
  "AWU": "Aeroline GmbH",
  "LNE": "Aerolane",
  "AUL": "Aeroflot-Nord",
  "ARD": "Aerocondor",
  "AOG": "Aero VIP",
  "BES": "Aero Services Executive",
  "MNG": "Aero Mongolia",
  "RLN": "Aero Lanka",
  "ARF": "Aero Flight",
  "CDP": "Aero Condor Peru",
  "BZL": "Aero Brazil",
  "AEB": "Aero Benin",
  "EAY": "Aero Airlines",
  "AXZ": "Aereonautica militare",
  "ADK": "ADC Airlines",
  "DHI": "Adam Air",
  "CYD": "Access Air",
  "ABX": "ABX Air",
  "CAV": "Calm Air",
  "TUS": "ABSA - Aerolinhas Brasileiras",
  "AAB": "Abelag Aviation",
  "ABE": "Aban Air",
  "MLA": "40-Mile Air",
  "VA3": "3 Valleys Airlines",
  "RNX": "1Time Airline",
  "N12": "12 North",
  "WSW": "Swoop",
  "ROU": "Air Canada Rouge",
  "OYO": "Oyonnair",
  "EJU": "EasyJet",
  "EZS": "EasyJet Switzerland",
  "NAK": "Nok Air",
  "LRQ": "Luxembourg Air Ambulance",
  "SAMU": "Hélicopter du SAMU",
  "FJO": "Flexjet Operations Malta",
  "FSF": "Flight Safety Foundation",
  "ELEC": "Electra Airways",
  "NJE": "National Jet Express"
}
