export const airlines = {
  "AAF": { iata: "ZI", name: "Aigle Azur (France)" },
  "AAL": { iata: "AA", name: "American Airlines (États-Unis)" },
  "AAR": { iata: "OZ", name: "Asiana Airlines (Corée du Sud)" },
  "AAW": { iata: "8U", name: "Afriqiyah Airways" },
  "AAY": { iata: "G4", name: "Allegiant Air (États-Unis)" },
  "ABH": { iata: "DF", name: "Aerolineas de Baleares Aebal (Espagne)" },
  "ABB": { iata: "OO", name: "Air Belgium (Belgique)" },
  "ARU": { iata: "AG", name: "Aruba airlines (Aruba)" },
  "ABQ": { iata: "PA", name: "Airblue (Pakistan)" },
  "ABY": { iata: "G9", name: "Air Arabia (Émirats arabes unis)" },
  "ACA": { iata: "AC", name: "Air Canada (Canada)" },
  "ACI": { iata: "SB", name: "Aircalin (Nouvelle-Calédonie, France)" },
  "ACK": { iata: "DV", name: "Nantucket Airlines (Nouvelle-Angleterre)" },
  "ADB": { iata: "J0", name: "Antonov Airlines (Ukraine)" },
  "ADE": { iata: "ZY", name: "Ada Air (Albanie)" },
  "ADH": { iata: "AP", name: "Air One (Italie)" },
  "ADO": { iata: "HD", name: "Hokkaido International Airlines (Japon)" },
  "ADR": { iata: "JP", name: "Adria Airways (Slovénie)" },
  "AEA": { iata: "UX", name: "Air Europa Lineas Aereas (Espagne)" },
  "AEE": { iata: "A3", name: "Aegean Airlines (Grèce)" },
  "AEF": { iata: "AE", name: "Aero Lloyd (Allemagne)" },
  "AEH": { iata: "NL", name: "Amelia International (France)" },
  "AEL": { iata: "PE", name: "Air Europe SpA (Italie, cf. Volare Web)" },
  "AEN": { iata: "AN", name: "Andorra Airlines" },
  "AES": { iata: "VX", name: "ACES" },
  "AEU": { iata: "5W", name: "Astraeus Airlines (Royaume-Uni)" },
  "AEW": { iata: "VV", name: "Aerosvit (Ukraine)" },
  "AFL": { iata: "SU", name: "Aeroflot Russian Airlines (Russie)" },
  "AFR": { iata: "AF", name: "Air France (France)" },
  "AGN": { iata: "GN", name: "Air Gabon (Gabon)" },
  "AHK": { iata: "LD", name: "Air Hong Kong" },
  "AHW": { iata: "HT", name: "Aeromist-Kharkiv (Ukraine)" },
  "AHY": { iata: "J2", name: "Azerbaijan Airlines" },
  "AIA": { iata: "U3", name: "Avies (Estonie)" },
  "AIC": { iata: "AI", name: "Air India" },
  "AIQ": { iata: "FD", name: "Thai AirAsia" },
  "AIZ": { iata: "IZ", name: "Arkia Israeli Airlines (Israël)" },
  "AJX": { iata: "NQ", name: "Air Japan" },
  "AKL": { iata: "4A", name: "Air Kiribati, (Kiribati)" },
  "ALD": { iata: "AL", name: "Air Leisure (Égypte)" },
  "ALK": { iata: "UL", name: "SriLankan Airlines (Sri Lanka)" },
  "AMC": { iata: "KM", name: "Air Malta (Malte)" },
  "AML": { iata: "QM", name: "Air Malawi" },
  "AMX": { iata: "AM", name: "Aeroméxico (Mexique)" },
  "ANA": { iata: "NH", name: "All Nippon Airways (Japon)" },
  "ANG": { iata: "PX", name: "Air Niugini (Papouasie-Nouvelle-Guinée)" },
  "ANS": { iata: "YW", name: "Air Nostrum L.A.M.S.A." },
  "ANZ": { iata: "NZ", name: "Air New Zealand (Nouvelle-Zélande)" },
  "APF": { iata: "A6", name: "Asia Pacific Airlines (Suède)" },
  "APN": { iata: null, name: "Alpine Airlines (France)" },
  "ARG": { iata: "AR", name: "Aerolíneas Argentinas (Argentine)" },
  "ASA": { iata: "AS", name: "Alaska Airlines (États-Unis)" },
  "ASD": { iata: "4D", name: "Air Sinai" },
  "ASH": { iata: "YV", name: "Mesa Airlines (États-Unis)" },
  "ASL": { iata: "JU", name: "Air Serbia (Serbia)" },
  "ASZ": { iata: "OB", name: "Astrakhan Airlines (Russie)" },
  "AUA": { iata: "OS", name: "Austrian Airlines (Autriche)" },
  "AUB": { iata: "IQ", name: "Augsburg Airways GmbH (Allemagne)" },
  "AUH": { iata: "MO", name: "Abu Dhabi Amiri Flight" },
  "AUI": { iata: "PS", name: "Ukraine International Airlines (Ukraine)" },
  "AUT": { iata: "AU", name: "Austral Lineas Aéreas (Argentine)" },
  "AUZ": { iata: "AO", name: "Australian Airlines (Australie)" },
  "AVA": { iata: "AV", name: "Avianca (Colombie)" },
  "AVE": { iata: "VE", name: "Avensa (Venezuela)" },
  "AVI": { iata: "A0", name: "L'avion (France)" },
  "AVN": { iata: "NF", name: "Air Vanuatu (Vanuatu)" },
  "AWI": { iata: "ZW", name: "Air Wisconsin (États-Unis)" },
  "AWP": { iata: null, name: "Air West (France)" },
  "AWW": { iata: "6G", name: "Air Wales (Royaume-Uni)" },
  "AXB": { iata: "IX", name: "Air India Express (Inde)" },
  "AXM": { iata: "AK", name: "Air Asia Sen (Malaisie)" },
  "AXY": { iata: "6V", name: "Axis Airways (France)" },
  "AYZ": { iata: "3G", name: "Atlant-Soyuz Airlines" },
  "AZA": { iata: "AZ", name: "Alitalia (Italie)" },
  "AZU": { iata: "AD", name: "Azul Linhas Aereas (Brésil)" },
  "AZW": { iata: "UM", name: "Air Zimbabwe" },
  "BAG": { iata: "DI", name: "Deutsche BA (Allemagne)" },
  "BAH": { iata: "BY", name: "Thomsonfly (Royaume-Uni)" },
  "BAV": { iata: "QH", name: "Bamboo Airways (Vietnam)" },
  "BAW": { iata: "BA", name: "British Airways (Royaume-Uni)" },
  "BBC": { iata: "BG", name: "Biman Bangladesh Airlines (Bangladesh)" },
  "BBG": { iata: null, name: "Bluebird Airways (Grèce)" },
  "BBO": { iata: "F7", name: "flybaboo (Suisse)" },
  "BBR": { iata: "S3", name: "Santa Barbara Airlines (Venezuela)" },
  "BCF": { iata: "B4", name: "B.A.C.H. Flugbetriebs (Allemagne)" },
  "BCS": { iata: "QY", name: "European Air Transport Leipzig (cargo)" },
  "BCY": { iata: "WX", name: "Cityjet" },
  "BEE": { iata: "BE", name: "flybe (Royaume-Uni)" },
  "BEL": { iata: "SN", name: "Brussels Airlines (Belgique)" },
  "BER": { iata: "AB", name: "Air Berlin (Allemagne)" },
  "BHA": { iata: "U4", name: "Buddha Air (Népal)" },
  "BIE": { iata: "ML", name: "Air Méditerranée" },
  "BKP": { iata: "PG", name: "Bangkok Airways" },
  "BLE": { iata: "4Y", name: "Blue Line" },
  "BLV": { iata: "B3", name: "Bellview Airlines (Nigeria)" },
  "BLX": { iata: "6B", name: "TUIfly Nordic (Suède)" },
  "BMM": { iata: "8A", name: "Atlas Blue (Maroc)" },
  "BMR": { iata: "BM", name: "BMI Regional (Royaume-Uni)" },
  "BOS": { iata: "LV", name: "OpenSkies (France)" },
  "BOT": { iata: "BP", name: "Air Botswana (Botswana)" },
  "BOU": { iata: "BO", name: "Bouraq Indonesia Airlines (Indonésie)" },
  "BPA": { iata: "BV", name: "Blue Panorama Airlines (Italie)" },
  "BRA": { iata: "BU", name: "Braathens (Norvège)" },
  "BRU": { iata: "B2", name: "Belavia (Biélorussie)" },
  "BRZ": { iata: "E5", name: "Samara Airlines (Russie)" },
  "BTC": { iata: "V9", name: "Bashkir Airlines" },
  "BTI": { iata: "BT", name: "Air Baltic (Lettonie)" },
  "BUB": { iata: "ZN", name: "Air Bourbon" },
  "BWA": { iata: "BW", name: "BWIA West Indies Airways (Trinité-et-Tobago)" },
  "BYU": { iata: "BM", name: "Bayu Indonesia Air (Indonésie)" },
  "BZH": { iata: "DB", name: "Brit Air" },
  "CAI": { iata: "XC", name: "Corendon (Turquie)" },
  "CAL": { iata: "CI", name: "China Airlines (Taiwan)" },
  "CBJ": { iata: "JD", name: "Beijing Capital Airlines" },
  "CCA": { iata: "CA", name: "Air China (Chine)" },
  "CCM": { iata: "XK", name: "Air Corsica" },
  "CDG": { iata: "SC", name: "Shandong Airlines (Chine)" },
  "CDO": { iata: "OT", name: "Tchadia Airlines (Tchad)" },
  "CDN": { iata: "CP", name: "Canadian Airlines International" },
  "CEB": { iata: "5J", name: "Cebu Pacific Air (Philippines)" },
  "CES": { iata: "MU", name: "China Eastern Airlines (Chine)" },
  "CFG": { iata: "DE", name: "Condor (Allemagne)" },
  "CHF": { iata: "X7", name: "Chitaavia (Russie)" },
  "CHP": { iata: "6A", name: "Aviacsa (Mexique)" },
  "CHQ": { iata: "RP", name: "Chautauqua Airlines" },
  "CIU": { iata: "A2", name: "Cielos del Peru (Pérou)" },
  "CLH": { iata: "CL", name: "Lufthansa CityLine GmbH (Allemagne)" },
  "CLW": { iata: "C0", name: "Centralwings (Pologne)" },
  "CMI": { iata: "CS", name: "Continental Micronesia" },
  "CMP": { iata: "CM", name: "Copa Airlines (Panama)" },
  "CND": { iata: "CD", name: "Coendon Dutch Airlines (Pays-Bas)" },
  "CPA": { iata: "CX", name: "Cathay Pacific Airways (Hong Kong)" },
  "CPE": { iata: "9K", name: "Cape Air (États-Unis)" },
  "CRF": { iata: "OR", name: "Crimea Air (Ukraine)" },
  "CRK": { iata: "HX", name: "Hong-Kong Airlines (Chine)" },
  "CRL": { iata: "SS", name: "Corsair International (France)" },
  "CSA": { iata: "OK", name: "CSA Czech Airlines (République tchèque)" },
  "CSH": { iata: "FM", name: "Shanghai Airlines (Chine)" },
  "CSN": { iata: "CZ", name: "China Southern Airlines (Chine)" },
  "CST": { iata: "BX", name: "Coast Air (Norvège)" },
  "CTN": { iata: "OU", name: "Croatia Airlines (Croatie)" },
  "CUB": { iata: "CU", name: "Cubana (Cuba)" },
  "CVA": { iata: "CV", name: "Air Chathams (Nouvelle-Zélande)" },
  "CXT": { iata: "DQ", name: "Coastal Air Transport" },
  "CYH": { iata: "3Q", name: "China Yunnan Airlines" },
  "DAH": { iata: "AH", name: "Air Algérie (Algérie)" },
  "DAL": { iata: "DL", name: "Delta Air Lines" },
  "DAO": { iata: "D3", name: "Daallo Airlines (Somalie et Djibouti)" },
  "DEX": { iata: "DM", name: "Asian Air (Thailand)" },
  "DJT": { iata: "B0", name: "La Compagnie (France)" },
  "DKH": { iata: "HO", name: "Juneyao Airlines (Chine)" },
  "DKN": { iata: "DN", name: "Fly Deccan (Inde)" },
  "DLA": { iata: "EN", name: "Air Dolomiti (Italie)" },
  "DLH": { iata: "LH", name: "Deutsche Lufthansa AG (Allemagne)" },
  "DMO": { iata: "E3", name: "Domodedovo Airlines (Russie)" },
  "DNV": { iata: "D9", name: "Donavia (Russie)" },
  "DRK": { iata: "KB", name: "Druk Air (Bhoutan)" },
  "DSB": { iata: "DS", name: "Air Sénégal" },
  "DSL": { iata: "D8", name: "Diamond Sakha Airlines" },
  "DTA": { iata: "DT", name: "TAAG Angola Airlines" },
  "DTR": { iata: "DX", name: "Danish Air Transport (Danemark)" },
  "DUO": { iata: "VB", name: "Duo Airways (Royaume-Uni)" },
  "EAF": { iata: "E7", name: "European AirCharter" },
  "EAI": { iata: "EA", name: "Emerald Airlines" },
  "EDW": { iata: "WK", name: "Edelweiss Air" },
  "EEZ": { iata: "GJ", name: "Eurofly (Italie)" },
  "EFC": { iata: null, name: "Air Mana" },
  "EIN": { iata: "EI", name: "Aer Lingus (Irlande)" },
  "ELY": { iata: "LY", name: "El Al (Israël)" },
  "ENK": { iata: "G5", name: "Enkor Airlines" },
  "ETD": { iata: "EY", name: "Etihad (Émirats arabes unis)" },
  "ETH": { iata: "ET", name: "Ethiopian Airlines" },
  "ETL": { iata: null, name: "Patterson Aviation Company (États-Unis)" },
  "EVA": { iata: "BR", name: "EVA Air (Taïwan)" },
  "EZY": { iata: "U2", name: "EasyJet (Royaume-Uni)" },
  "FAB": { iata: "7F", name: "First Air" },
  "FDB": { iata: "FZ", name: "FlyDubai" },
  "FDX": { iata: "FX", name: "FedEx Corporation (États-Unis)" },
  "FEY": { iata: "N5", name: "FLYeasy (Inde)" },
  "FHY": { iata: "FH", name: "Free Bird Airlines (Turquie)" },
  "FIN": { iata: "AY", name: "Finnair Oyj (Finlande)" },
  "FJI": { iata: "FJ", name: "Fiji Airways (Fidji)" },
  "FLI": { iata: "RC", name: "Atlantic Airways" },
  "FQA": { iata: "QO", name: "Quikjet (Inde)" },
  "FRI": { iata: "FW", name: "Ibex Airlines (Japon)" },
  "FTT": { iata: "F9", name: "Frontier Airlines (États-Unis)" },
  "FWI": { iata: "TX", name: "Air Caraïbes (Guadeloupe)" },
  "GFA": { iata: "G4", name: "Allegiant Air (États-Unis)" },
  "GFA": { iata: "G4", name: "Allegiant Air (États-Unis)" },
  "GFL": { iata: "VF", name: "Van Air Europe" },
  "GGC": { iata: "GK", name: "Jetstar Japan" },
  "GIC": { iata: "IQ", name: "Great Lakes Airlines (États-Unis)" },
  "GJH": { iata: "5J", name: "Jetstar Asia Airways (Singapour)" },
  "GLL": { iata: "Z6", name: "GLL Airlines" },
  "GLO": { iata: "GL", name: "Globus Airlines (Russie)" },
  "GMR": { iata: "AI", name: "Air India" },
  "GNG": { iata: "6H", name: "GoAir (Inde)" },
  "GOL": { iata: "G3", name: "Gol Linhas Aéreas Inteligentes (Brésil)" },
  "GPA": { iata: "GP", name: "Guine Bissau Airlines" },
  "GPS": { iata: "P4", name: "Gippsland Air Services" },
  "GWI": { iata: "GW", name: "City Airways (Thaïlande)" },
  "GXL": { iata: "3G", name: "Go! (États-Unis - Hawaii)" },
  "HAD": { iata: "3H", name: "Hahn Air" },
  "HAL": { iata: "HA", name: "Hawaiian Airlines (États-Unis)" },
  "HAM": { iata: "HM", name: "Air Seychelles" },
  "HAT": { iata: "HT", name: "Haiti Air" },
  "HAV": { iata: "HV", name: "Havers Aviation" },
  "HBC": { iata: "HB", name: "Hebei Airlines" },
  "HDA": { iata: "HD", name: "Hokkaido Air System" },
  "HES": { iata: "W8", name: "Safi Airways" },
  "HFA": { iata: "H2", name: "Hahn Air" },
  "HIC": { iata: "HH", name: "Highland Airways (Royaume-Uni)" },
  "HIL": { iata: "HX", name: "Hong Kong Airlines" },
  "HKA": { iata: "UO", name: "HK Express" },
  "HLA": { iata: "HH", name: "Highland Airways" },
  "HNA": { iata: "HU", name: "Hainan Airlines" },
  "HNB": { iata: "R3", name: "Transavia France" },
  "HNE": { iata: "HZ", name: "Horizon Airlines (Australie)" },
  "HNK": { iata: "HN", name: "Hankyu Airlines" },
  "HOG": { iata: "HG", name: "Hogestar Airlines" },
  "HOP": { iata: "A5", name: "HOP! (France)" },
  "HPL": { iata: "H1", name: "Hewa Bora Airways" },
  "HRH": { iata: "2H", name: "Hahn Air Lines" },
  "HRT": { iata: "HT", name: "Haiti Air" },
  "HSA": { iata: "HS", name: "Hewa Bora Airways" },
  "HSK": { iata: "HK", name: "Hokkaido International Airlines" },
  "HSP": { iata: "HP", name: "America West Airlines" },
  "HTR": { iata: "HT", name: "Haiti Air" },
  "HTW": { iata: "HW", name: "Hatton National Airlines" },
  "HUA": { iata: "HU", name: "Hainan Airlines" },
  "HYE": { iata: "HY", name: "Himalaya Airlines" },
  "HYV": { iata: "HY", name: "Hainan Airlines" },
  "IAG": { iata: null, name: "EPAG - Groupe Air France" },
  "IAW": { iata: "IA", name: "Iraqi Airways" },
  "IBB": { iata: "NT", name: "Binter Canarias (Espagne)" },
  "IBE": { iata: "IB", name: "Iberia Líneas Aéreas de España (Espagne)" },
  "ICB": { iata: "HH", name: "Islandsflug (Islande)" },
  "ICE": { iata: "FI", name: "Icelandair (Islande)" },
  "IDE": { iata: "DH", name: "Independence Air" },
  "IGO": { iata: "6E", name: "IndiGo (Inde)" },
  "IRA": { iata: "IR", name: "Iran Air" },
  "IRC": { iata: "EP", name: "Iran Aseman Airlines (Iran)" },
  "IRB": { iata: "B9", name: "Iran Air Tours (Iran)" },
  "IRM": { iata: "W5", name: "Mahan Airlines (Iran)" },
  "ISR": { iata: "6H", name: "Israir Airlines and Tourism Limited (Israël)" },
  "ISS": { iata: "IG", name: "Air Italy S.p.A. (Italie)" },
  "ITY": { iata: "AZ", name: "ITA Airways (Italie)" },
  "IWD": { iata: "TY", name: "Iberworld (Espagne)" },
  "IYE": { iata: "IY", name: "Yemenia (Yemen)" },
  "JAZ": { iata: "JO", name: "JALways (Japon) (compagnie disparue)" },
  "JAW": { iata: "JO", name: "Jasmin Airways (Tunisie)" },
  "JBA": { iata: "JB", name: "Helijet" },
  "JBO": { iata: "JX", name: "Jambojet (Kenya)" },
  "JBU": { iata: "B6", name: "jetBlue Airways (États-Unis)" },
  "JNA": { iata: "LJ", name: "Jin Air (South Korea)" },
  "JON": { iata: "JN", name: "Joon (groupe Air France) (France)" },
  "JST": { iata: "JQ", name: "Jetstar Airways" },
  "JTA": { iata: "NU", name: "Japan Transocean Air (groupe Japan Airlines) (Japon)" },
  "JTG": { iata: "??", name: "Jettime (Danemark)" },
  "JXX": { iata: "GX", name: "JetX Airlines (Islande/Italie)" },
  "JYH": { iata: "AQ", name: "9 Air (Chine)" },
  "KAC": { iata: "KU", name: "Kuwait Airways" },
  "KAE": { iata: "3Y", name: "Kartika Airlines (Indonésie)" },
  "KAZ": { iata: "U9", name: "Tatarstan JSC Aircompany" },
  "KFA": { iata: "KW", name: "Kelowna Flightcraft" },
  "KFB": { iata: "KF", name: "Blue1 Oy (précédemment Air Botnia) (Finlande)" },
  "KGL": { iata: "7K", name: "Kogalymavia Air Company" },
  "KHB": { iata: "H8", name: "Dalavia (Russie)" },
  "KHO": { iata: "X9", name: "Khors Aircompany (Ukraine)" },
  "KIL": { iata: "GW", name: "Kuban Airlines (Russie, Krasnodar)" },
  "KLC": { iata: "WA", name: "KLM City Hopper" },
  "KLM": { iata: "KL", name: "KLM Royal Dutch Airlines" },
  "KMZ": { iata: "??", name: "Comores Aviation" },
  "KNE": { iata: "XY", name: "Flynas (Arabie saoudite)" },
  "KRN": { iata: "U5", name: "Karinou Airlines" },
  "KQA": { iata: "KQ", name: "Kenya Airways" },
  "KYV": { iata: "YK", name: "Cyprus Turkish Airlines (ou Air Kibris) (Chypre, partie occupée par la Turquie)" },
  "KZR": { iata: "KC", name: "Air Astana" },
   "LAA": { iata: "LN", name: "Libyan Arab Airlines" },
  "LAM": { iata: "TM", name: "LAM Linhas Aereas de Moçambique (Mozambique)" },
  "LAN": { iata: "LA", name: "LATAM Chile (Chili)" },
  "LAP": { iata: "PZ", name: "TAM Mercosur (précédemment Lineas Aereas Paraguayas) (Paraguay)" },
  "LAV": { iata: "VH", name: "Aeropostal Alas" },
  "LBC": { iata: "LV", name: "Albanian Airlines MAK S.H.P.K. (Albanie)" },
  "LBT": { iata: "BJ", name: "Nouvelair Tunisia (Tunisie)" },
  "LCD": { iata: "ZE", name: "Líneas Aéreas Azteca (Mexique)" },
  "LDA": { iata: "NG", name: "Lauda Air Luftfahrt AG (Autriche) appartient à Austrian Airlines" },
  "LDI": { iata: "L4", name: "Lauda Air S.p.A. (Italie)" },
  "LIA": { iata: "LI", name: "Liat (ex Antilles britanniques)" },
  "LIL": { iata: "TE", name: "Lithuanian Airlines (Lituanie)" },
  "LIV": { iata: "??", name: "Air Livonia (Estonie)" },
  "LLM": { iata: "YL", name: "Yamal (Russie)" },
  "LLR": { iata: "9I", name: "Alliance Air (Inde)" },
  "LNI": { iata: "JT", name: "Lion Air (Indonésie)" },
  "LOF": { iata: "AX", name: "Trans States Airlines/programme AmericanConnection (États-Unis)" },
  "LOT": { iata: "LO", name: "LOT Polish Airlines (Pologne)" },
  "LPV": { iata: "A6", name: "Air Alps Aviation (Autriche)" },
  "LRC": { iata: "LR", name: "Lacsa/TACA" },
  "LTE": { iata: "XO", name: "Volar Airlines (précédemment LTE International Airways) (Espagne)" },
  "LTU": { iata: "LT", name: "LTU International Airways (Allemagne)" },
  "LVG": { iata: "LM", name: "Livingston S.p.A. (Italie)" },
  "LXR": { iata: "LK", name: "Air Luxor (Portugal)" },
  "LZB": { iata: "FB", name: "Bulgaria Air" },
  "MAH": { iata: "MA", name: "Malév Hungarian Airlines (Hongrie)" },
  "MAK": { iata: "IN", name: "MAT Macedonian Airlines (Macédoine)" },
  "MAS": { iata: "MH", name: "Malaysia Airlines" },
  "MAU": { iata: "MK", name: "Air Mauritius Ltd" },
  "MCK": { iata: "CC", name: "Macair Airlines (Australie)" },
  "MCM": { iata: "YO", name: "Heli Air Monaco" },
  "MDA": { iata: "AE", name: "Mandarin Airlines (Taïwan)" },
  "MDG": { iata: "MD", name: "Air Madagascar" },
  "MEP": { iata: "YX", name: "Midwest Connect" },
  "MES": { iata: "XJ", name: "Mesaba Airlines (États-Unis)" },
  "MGL": { iata: "MR", name: "Mongolian Airlines (Mongolie)" },
  "MGX": { iata: "YM", name: "Montenegro Airlines (Serbie-et-Monténégro)" },
  "MLD": { iata: "9U", name: "Air Moldova (Moldavie)" },
  "MLV": { iata: "H5", name: "Magadan Airlines (Russie)" },
  "MMA": { iata: "8M", name: "Myanmar Airways International (Birmanie)" },
  "MMZ": { iata: "MM", name: "euroAtlantic Airways (Portugal)" },
  "MNB": { iata: "MB", name: "MNG Cargo Airlines" },
  "MON": { iata: "ZB", name: "Monarch Airlines (Royaume-Uni)" },
  "MPD": { iata: "A7", name: "Air Comet (nom commercial Air Plus Comet) (Espagne)" },
  "MPH": { iata: "MP", name: "Martinair Holland (Pays-Bas)" },
  "MRS": { iata: "CW", name: "Air Marshall Islands (îles Marshall)" },
  "MSI": { iata: "M9", name: "Motor Sich (Ukraine)" },
  "MSR": { iata: "MS", name: "Egypt Air" },
  "MVD": { iata: "KV", name: "Kavminvodyavia (Russie)" },
  "MVL": { iata: "H5", name: "Magadan Airlines" },
  "MXA": { iata: "MX", name: "Mexicana" },
  "MYT": { iata: "VZ", name: "MyTravel Airways (Danemark / Royaume-Uni)" },
  "MYW": { iata: "8I", name: "MyAir" },
  "NCA": { iata: "KZ", name: "Nippon Cargo Airlines" },
  "NGK": { iata: "??", name: "Oriental Air Bridge (Japon)" },
  "NIG": { iata: "AJ", name: "AeroContractors Company of Nigeria (Nigeria)" },
  "NLY": { iata: "HG", name: "FlyNiki (Autriche)" },
  "NKS": { iata: "NK", name: "Spirit Airlines (États-Unis)" },
  "NMB": { iata: "SW", name: "Air Namibia (Namibie)" },
  "NOS": { iata: "NO", name: "Neos (Italie)" },
  "NOV": { iata: "RD", name: "Alitalia Team (fusionné avec Alitalia en 2002)" },
   "NWA": { iata: "NW", name: "Northwest Airlines (États-Unis)" },
  "NWS": { iata: "N4", name: "Nordwind (Russie)" },
  "OAG": { iata: "CR", name: "OAG Worldwide (Royaume-Uni)" },
  "OAI": { iata: "OA", name: "Olympic Airways (Grèce)" },
  "OAS": { iata: "WY", name: "Oman Air" },
  "OAW": { iata: "2L", name: "Helvetic (Suisse)" },
  "OCM": { iata: "UQ", name: "O'Connor Airlines (Australie)" },
  "OGE": [
    { iata: "KK", name: "Atlasjet Uluslararasi Havacilik / Atlasjet International Airways (Turquie)" },
    { iata: "2U", name: "Atlasjet Uluslararasi Havacilik / Atlasjet International Airways (Turquie)" }
  ],
  "OGN": { iata: "QO", name: "Origin Pacific (Nouvelle-Zélande)" },
  "OKS": { iata: "SO", name: "Slok Air Gambia (Gambie)" },
  "OMS": { iata: "N3", name: "Omskavia Airlines (Russie)" },
  "ORB": { iata: "R2", name: "Orenburg Airlines (Russie)" },
  "PAL": { iata: "PR", name: "Philippine Airlines (Philippines)" },
  "PAO": { iata: "PH", name: "Polynesian Airlines (Samoa)" },
  "PDA": { iata: null, name: "Podillia Avia (Ukraine)" },
  "PIA": { iata: "PK", name: "Pakistan International Airlines (Pakistan)" },
  "PIC": { iata: "BL", name: "Pacific Airlines (Viêt Nam)" },
  "PLI": { iata: "PL", name: "Aeroperu (Pérou)" },
  "PLK": { iata: "FV", name: "Pulkovo Aviation Entreprise (Russie)" },
  "PMN": { iata: "P2", name: "UTair (Russie)" },
  "PNW": { iata: "PF", name: "Palestinian Airlines (Palestine)" },
  "PPL": { iata: "OP", name: "Air Pegasus (Inde)" },
  "PRI": { iata: "WP", name: "Island Air" },
  "PUA": { iata: "PU", name: "Pluna (Pluna Lineas Aereas Uruguayas) (Uruguay)" },
  "PGT": { iata: "H9", name: "Pegasus Airlines (Turquie)" },
  "QFA": { iata: "QF", name: "Qantas Airways (Australie)" },
  "QXE": { iata: "QX", name: "Horizon Air" },
  "QTR": { iata: "QR", name: "Qatar Airways (Qatar)" },
   "RAE": { iata: "YS", name: "Régional (compagnie aérienne européenne)" },
  "RAM": { iata: "AT", name: "Royal Air Maroc (Maroc)" },
  "RAR": { iata: "GZ", name: "Air Rarotonga (îles Cook)" },
  "RBA": { iata: "BI", name: "Royal Brunei Airlines (Brunei)" },
  "REA": { iata: "RE", name: "Aer Arann" },
  "REU": { iata: "UU", name: "Air Austral (Réunion)" },
  "RIE": { iata: "", name: "ARIELLA AIRLINES S.A (Burkina Faso)" },
  "RIV": { iata: "GP", name: "APG Airlines (France)" },
  "RJA": { iata: "RJ", name: "Royal Jordanian (Jordanie)" },
  "RLA": { iata: "A5", name: "Airlinair (France)" },
  "RNA": { iata: "RA", name: "Royal Nepal Airlines Corporation" },
  "ROM": { iata: "BQ", name: "Aeromar Airlines (République dominicaine)" },
  "RON": { iata: "ON", name: "Our Airline (Nauru)" },
  "ROT": { iata: "RO", name: "Tarom Transporturile Aeriene Romane (Roumanie)" },
  "RPB": { iata: "P5", name: "AeroRepublica (Colombie)" },
  "RRE": { iata: "RE", name: "Régional Europe (France)" },
  "RSO": { iata: "", name: "Aero Asia (Pakistan)" },
  "RSR": { iata: "BF", name: "AeroService (Colombie)" },
  "RTQ": { iata: "RT", name: "Air Turquoise (France)" },
  "RVL": { iata: "DO", name: "Air Vallée (Italie)" },
  "RYR": { iata: "FR", name: "Ryanair (Irlande)" },
  "RZO": { iata: "S4", name: "SATA International (Portugal)" },
  "SAS": { iata: "SK", name: "Scandinavian Airlines System" },
  "SAT": { iata: "SP", name: "SATA Air Açores (Portugal)" },
  "SAY": { iata: "CB", name: "Scot Airways (Royaume-Uni)" },
  "SBI": { iata: "S7", name: "Siberia Airlines" },
  "SBS": { iata: "BB", name: "Seaborne Airlines (États-Unis)" },
  "SCH": { iata: "AW", name: "Schreiner Airways (Pays-Bas)" },
  "SCO": { iata: "TZ", name: "Scoot (Singapour)" },
  "SCW": { iata: "TF", name: "Snålskjutsen (opérée par Malmö Aviation) (Suède)" },
  "SCX": { iata: "SY", name: "Sun Country (États-Unis)" },
  "SDM": { iata: "FV", name: "Rossiya" },
  "SEJ": { iata: "SG", name: "SpiceJet (Inde)" },
  "SER": { iata: "JR", name: "Aero California (Mexique)" },
  "SEY": { iata: "HM", name: "Air Seychelles" },
  "SIA": { iata: "SQ", name: "Singapore Airlines" },
  "SIB": { iata: "5M", name: "Sibaviatrans" },
  "SIC": { iata: "BM", name: "Air Sicilia (Italie)" },
  "SHU": { iata: "HZ", name: "SAT Airlines (Russie)" },
  "SJY": { iata: "SJ", name: "Sriwijaya Air (Indonesie)" },
  "SKX": { iata: "JZ", name: "Skyways AB" },
  "SKY": { iata: "BC", name: "Skymark Airlines (Japon)" },
  "SLK": { iata: "MI", name: "Silk Air (Singapour)" },
  "SLL": { iata: "6Q", name: "Slovak Airlines (Slovaquie)" },
  "SLM": { iata: "PY", name: "Surinam Airways (Suriname)" },
  "SOV": { iata: "6W", name: "Saravia (Saratov Airlines) (Russie)" },
  "SPM": { iata: "PJ", name: "Air Saint-Pierre (Saint-Pierre-et-Miquelon)" },
  "SRQ": { iata: "DG", name: "Eastern Pacific" },
  "SSV": { iata: "5G", name: "Skyservice Airlines (Can)" },
  "SUD": { iata: "SD", name: "Sudan Airways (Soudan)" },
  "SVA": { iata: "SV", name: "Saudi Arabian Airlines" },
  "SVK": { iata: "GM", name: "Air Slovakia (Slovaquie)" },
  "SVR": { iata: "U6", name: "Ural Airlines (Russie)" },
  "SWA": { iata: "WN", name: "Southwest Airlines" },
  "SWD": { iata: "A4", name: "Southern Winds (Argentine)" },
  "SWG": { iata: "WG", name: "Sunwing Airlines (Canada)" },
  "SWR": { iata: "LX", name: "Swiss International Air Lines Ltd (anciennement Crossair/Swissair)" },
  "SWR": { iata: "LX", name: "Swissair (précédemment) (Suisse)" },
  "SWU": { iata: "LZ", name: "Swiss Global Air Lines" },
  "SYR": { iata: "RB", name: "Syrianair" },
  "TAI": { iata: "TA", name: "Taca International Airlines (Salvador)" },
  "TAM": { iata: "JJ", name: "LATAM Brasil" },
  "TAO": { iata: "VW", name: "Aeromar (Mexique)" },
  "TAP": { iata: "TP", name: "TAP Air Portugal (Portugal)" },
  "TAR": { iata: "TU", name: "Tunisair" },
  "TAX": { iata: "XJ", name: "Thai AirAsia X" },
  "TCV": { iata: "VR", name: "TACV (Cape Verde Airlines) (Cap-Vert)" },
  "TCW": { iata: "FQ", name: "Thomas Cook Airlines Belgium" },
  "TCX": { iata: "MT", name: "Thomas Cook Airlines UK" },
  "TDM": { iata: "TQ", name: "Tandem Aero" },
  "TGA": { iata: "YT", name: "Air Togo" },
  "TGW": { iata: "TR", name: "Tiger Airways (Singapour)" },
  "TGZ": { iata: "A9", name: "Airzena Georgian Airlines (Géorgie)" },
  "THA": { iata: "TG", name: "Thai Airways International (Thaïlande)" },
  "THT": { iata: "TN", name: "Air Tahiti Nui (Polynésie française)" },
  "THY": { iata: "TK", name: "Turkish Airlines (Turquie)" },
  "TJT": { iata: "T7", name: "Twin Jet (France)" },
  "TLB": { iata: "??", name: "Atlantique Air Assistance (France)" },
  "TMA": { iata: "TL", name: "Trans Mediterranean Airways (TMA)" },
  "TMN": { iata: "HJ", name: "Tasman Cargo Airlines (Australie/Nouvelle-Zélande)" },
  "TPC": { iata: "TY", name: "Air Calédonie (France, Nouvelle-Calédonie)" },
  "TRA": { iata: "HV", name: "Transavia Airlines (Pays-Bas)" },
  "TRJ": { iata: "2T", name: "Trujet (Inde)" },
  "TRZ": { iata: "D9", name: "Prime Air Inc." },
  "TSC": { iata: "TS", name: "Air Transat (Canada)" },
  "TUA": { iata: "T5", name: "Turkménistan/Akhal" },
  "SEN": { iata: "UG", name: "Tunisair Express (ex Sevenair)" },
  "TUQ": { iata: "RT", name: "Air Turquoise" },
  "TVF": { iata: "TO", name: "Transavia France (France)" },
  "TVR": { iata: "T6", name: "Tavrey Airlines (Ukraine)" },
  "TVS": { iata: "QS", name: "Travel Service Airlines" },
  "TYR": { iata: "VO", name: "Tyrolean Airways (Autriche)" },
  "UAE": { iata: "EK", name: "Emirates (Émirats arabes unis)" },
  "UAL": { iata: "UA", name: "United Airlines Inc." },
  "UBA": { iata: "UB", name: "Myanmar Airways (Birmanie)" },
  "UCR": { iata: "DW", name: "Aero-Charter Airlines (Ukraine) ou Helicopter Shuttle ?" },
  "UDC": { iata: "7D", name: "Donbassaero (Ukraine)" },
  "UDN": { iata: "Z6", name: "Dniproavia (Ukraine)" },
  "UIA": { iata: "B7", name: "Uni Air (Taïwan)" },
  "UKM": { iata: "UF", name: "UM Airlines (Ukraine)" },
  "UKR": { iata: "6U", name: "Air Ukraine (Ukraine)" },
  "UKS": { iata: "6Z", name: "Ukrainian Cargo Airways (Ukraine)" },
  "UKW": { iata: "5V", name: "Lviv Airlines (Ukraine)" },
  "URG": { iata: "3N", name: "Air Urga (Ukraine)" },
  "URP": { iata: "ZK", name: "?? ARP 410 Airlines (Ukraine)" },
  "UYC": { iata: "UY", name: "Cameroon Airlines (Cameroun)" },
  "UTA": { iata: "UT", name: "UTair (Russie)" },
  "UZB": { iata: "HY", name: "Uzbekistan Airways" },
  "VAP": { iata: "9R", name: "Phuket Air" },
  "VDA": { iata: "VI", name: "Volga-Dnepr Airlines Joint Stock" },
  "VIR": { iata: "VS", name: "Virgin Atlantic Airways Ltd. (Royaume-Uni)" },
  "VLE": { iata: "VA", name: "Volare Web Volare Airlines SpA (Italie)" },
  "VLG": { iata: "VY", name: "Vueling Airlines (Espagne)" },
  "VLK": { iata: "XF", name: "Vladivostok Avia (Russie)" },
  "VLU": { iata: "VF", name: "Valuair (Singapour)" },
  "VOE": { iata: "V7", name: "Volotea (Espagne)" },
  "VOZ": { iata: "VA", name: "Virgin Australia" },
  "VRD": { iata: "VX", name: "Virgin America (États-Unis)" },
  "VRE": { iata: "F7", name: "Volare Airlines (Ukraine)" },
  "VSP": { iata: "VP", name: "VASP (Brésil)" },
  "VTA": { iata: "VT", name: "Air Tahiti (Polynésie française)" },
  "VTI": { iata: "UK", name: "TATA SIA Vistara (Inde)" },
  "VUN": { iata: "CI", name: "Air Ivoire (Côte d'Ivoire)" },
  "WAK": { iata: "K5", name: "Wings of Alaska" },
  "WBA": { iata: "FC", name: "Finncomm Airlines" },
  "WCP": { iata: "FE", name: "Primaris Airlines" },
  "WIA": { iata: "WM", name: "Winair" },
  "WIF": { iata: "WF", name: "Widerøe's Flyveselskap AS (Norvège), membre du groupe SAS" },
  "WJA": { iata: "WS", name: "WestJet (Canada)" },
  "WOA": { iata: "WO", name: "World Airways" },
  "WZZ": { iata: "W6", name: "Wizz Air" },
  "XAR": { iata: "XN", name: "Xpress Air" },
  "XAX": { iata: "D7", name: "AirAsia X" },
  "XJC": { iata: "XJ", name: "Xclusive Jet Charter" },
  "XLF": { iata: "SE", name: "XL Airways France (ex Star Airlines)" },
  "XRC": { iata: "7A", name: "Express Air Cargo (Tunisie)" },
  "YZR": { iata: "Y8", name: "Yangtze River Express Airlines" },
  "ZAL": { iata: "ZO", name: "Zoom Air (Inde)" },
  "ZBA": { iata: "ZB", name: "Air" },
  "ZWA": { iata: "ZW", name: "flymojo (Malaisie)" }
};